baseURL = "https://qbs.io"
languageCode = "en-us"
title = "Qbs"
theme = "qbs"

[params]
    description = "Better build system."

[markup.goldmark.renderer]
    unsafe = "true"

[menu]

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
        weight = -110

    [[menu.main]]
        identifier = "docs"
        name = "Documentation"
        url = "/docs"
        weight = -105

    [[menu.main]]
        identifier = "download"
        name = "Download"
        url = "/download"
        weight = -90
