name = "qbs"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A theme for Qbs.io"
homepage = "http://qbs.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Janet Blackquill"
  homepage = ""
